In [2]:
import torch
import numpy as np

In [2]:
lst=[1,2,3,4]
n1=np.array(lst)

In [3]:
t1=torch.from_numpy(n1)
t1

tensor([1, 2, 3, 4], dtype=torch.int32)

In [4]:
t1[3]=300

In [5]:
n1

array([  1,   2,   3, 300])

**Observation**
- Here for a tensor we have the array element change

In [6]:
t2=torch.tensor(n1)
t2

tensor([  1,   2,   3, 300], dtype=torch.int32)

In [7]:
t2[3]=120

In [8]:
t2

tensor([  1,   2,   3, 120], dtype=torch.int32)

In [9]:
n1

array([  1,   2,   3, 300])

In [10]:
torch.zeros(2,3,dtype=torch.float32)
torch.ones(2,4,dtype=torch.float32)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [12]:
a[:,1:3]

tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14]], dtype=torch.int32)

In [13]:
a=torch.tensor([1,2,3],dtype=torch.float)
b=torch.tensor([1,2,3],dtype=torch.float)

In [14]:
a+b
torch.add(a,b)

tensor([2., 4., 6.])

In [15]:
c=torch.zeros(3)

In [16]:
torch.add(a,b,out=c)

tensor([2., 4., 6.])

In [17]:
c.sum()

tensor(12.)

In [18]:
a.mul(b)

tensor([1., 4., 9.])

In [19]:
a.dot(b)

tensor(14.)

In [20]:
a1=torch.tensor([[1,2,3],[2,3,5]],dtype=torch.float)
b1=torch.tensor([[2,3],[1,2],[1,4]],dtype=torch.float)
torch.matmul(a1,b1)

tensor([[ 7., 19.],
        [12., 32.]])

In [21]:
a1@b1

tensor([[ 7., 19.],
        [12., 32.]])

In [22]:
torch.mm(a1,b1)

tensor([[ 7., 19.],
        [12., 32.]])

**Backpropagation**

In [3]:
x=torch.tensor(4.0,requires_grad=True)

In [4]:
x

tensor(4., requires_grad=True)

In [5]:
y=x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [6]:
y.backward()

In [7]:
x.grad

tensor(8.)

In [8]:
List1=[[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]]

In [9]:
x1=torch.tensor(List1,requires_grad=True)

In [12]:
y=x1**3+x1**2

In [13]:
y

tensor([[  2.,  12.,  36.],
        [ 80., 150., 252.],
        [392., 576., 810.]], grad_fn=<AddBackward0>)

In [14]:
z=y.sum()
z

tensor(2310., grad_fn=<SumBackward0>)

In [15]:
z.backward()

In [16]:
x1.grad

tensor([[  5.,  16.,  33.],
        [ 56.,  85., 120.],
        [161., 208., 261.]])